#! /bin/bash

export CUDA_VISIBLE_DEVICES=2

rm -rf output/3var/*
python main.py --num_nodes 3 --data_seed 42 --anneal --save_path ./output/3var --dataset_dir='../dag-gwg/datasets/3var'

rm -rf output/4var/*
python main.py --num_nodes 4 --data_seed 42 --anneal --save_path ./output/4var --dataset_dir='../dag-gwg/datasets/4var'

rm -rf output/7var/*
python main.py --num_nodes 7 --data_seed 42 --anneal --save_path ./output/7var --dataset_dir='../dag-gwg/datasets/7var'

rm -rf output/sachs/*
python main.py --num_nodes 11 --data_seed 42 --anneal --save_path ./output/sachs --dataset_dir='../dag-gwg/datasets/sachs'

mkdir output/20var-01
rm -rf output/20var-01/*
python main.py --num_nodes 20 --data_seed 42 --anneal --save_path ./output/20var-01 --dataset_dir='../dag-gwg/datasets/20var-01'
mkdir output/20var-02
rm -rf output/20var-02/*
python main.py --num_nodes 20 --data_seed 42 --anneal --save_path ./output/20var-02 --dataset_dir='../dag-gwg/datasets/20var-02'
mkdir output/20var-03
rm -rf output/20var-03/*
python main.py --num_nodes 20 --data_seed 42 --anneal --save_path ./output/20var-03 --dataset_dir='../dag-gwg/datasets/20var-03'
mkdir output/20var-04
rm -rf output/20var-04/*
python main.py --num_nodes 20 --data_seed 42 --anneal --save_path ./output/20var-04 --dataset_dir='../dag-gwg/datasets/20var-04'
mkdir output/20var-05
rm -rf output/20var-05/*
python main.py --num_nodes 20 --data_seed 42 --anneal --save_path ./output/20var-05 --dataset_dir='../dag-gwg/datasets/20var-05'
